// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Province_API.Infrastructure.Data;

#nullable disable

namespace Province_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Province_API.Core.Domain.Entities.AdminstrativeUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AdminstrativeUnitId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentId")
                        .HasColumnType("text")
                        .HasColumnName("parentId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("AdminstrativeUnitId");

                    b.ToTable("administrative_unit");
                });

            modelBuilder.Entity("Province_API.Core.Domain.Entities.AdminstrativeUnit", b =>
                {
                    b.HasOne("Province_API.Core.Domain.Entities.AdminstrativeUnit", null)
                        .WithMany("Children")
                        .HasForeignKey("AdminstrativeUnitId");
                });

            modelBuilder.Entity("Province_API.Core.Domain.Entities.AdminstrativeUnit", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
